import type {Metadata} from "next";
import "../globals.css";
import "./styles.css"
import {Be_Vietnam_Pro, Inter, Poppins} from "next/font/google"

import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import {ThemeProvider} from "@/app/components/ThemeProvider";
import {Toaster} from "@/components/ui/sonner";
import {SkeletonTheme} from "react-loading-skeleton";

config.autoAddCss = false

const inter = Inter({subsets: ['latin'], variable: '--font-inter', display: "swap"})
const vn = Be_Vietnam_Pro({weight: ['400'], subsets: ['latin'], variable: '--font-vn', display: "swap"})
const poppins = Poppins({weight: ['400', '500', '600', '700'], subsets: ['latin'], variable: '--font-poppins'})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LandingPageLayout({
                                              children,
                                          }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning
              className={`${inter.variable} ${vn.variable} ${poppins.variable} antialiased`}>
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SkeletonTheme baseColor="#202020" highlightColor="#444">
                {children}
            </SkeletonTheme>
            <Toaster/>
        </ThemeProvider>
        </body>
        </html>
    );
}
